/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner Health */
        get: operations["owner_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hunt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Hunt
         * @description Persist an encrypted request and return immediately with queued state.
         */
        post: operations["post_hunt_api_hunt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return queue state, plus result/outcomes after the run succeeds.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Run
         * @description Delete a run, its encrypted request metadata, audit events, and outcomes.
         */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Cancel a queued/running run through its authorized workspace.
         */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Outcomes
         * @description Append user-logged outcomes for a completed hunt.
         */
        post: operations["post_outcomes_api_runs__run_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Requeue Run
         * @description Move a dead-letter run back to queued through an authorized action.
         */
        post: operations["requeue_run_api_runs__run_id__requeue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_session_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_session_post"];
        /** Delete Session */
        delete: operations["delete_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Lightweight liveness check for the deployment platform.
         *
         *     HEAD is allowed because uptime monitors (UptimeRobot) probe with it.
         */
        get: operations["health_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CompanySource
         * @description Supported strategies for discovering a company's open roles.
         * @enum {string}
         */
        CompanySource: "greenhouse" | "lever" | "ashby" | "workday" | "smartrecruiters" | "workable" | "bespoke" | "google_jobs" | "scrape";
        /** DeleteResponse */
        DeleteResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * EmploymentType
         * @description Normalized employment types exposed by source adapters.
         * @enum {string}
         */
        EmploymentType: "full_time" | "contract" | "intern" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
        };
        /** HuntCreatedResponse */
        HuntCreatedResponse: {
            /**
             * Access Token
             * @description Legacy-compatible run capability. Practical workspaces authorize through the owner session and do not require this token.
             */
            access_token: string;
            /** Attempt Count */
            attempt_count: number;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Dead Lettered At */
            dead_lettered_at?: string | null;
            /** Failed At */
            failed_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Max Attempts */
            max_attempts: number;
            /** Queued At */
            queued_at?: string | null;
            /**
             * Reused
             * @description True when an idempotency key returned an existing run.
             * @default false
             */
            reused: boolean;
            /** Run Id */
            run_id: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "dead_letter";
        };
        /**
         * HuntRequestPayload
         * @description Validated user request stored in the encrypted queue envelope.
         */
        HuntRequestPayload: {
            /** @description Filters for the hunt. */
            criteria: components["schemas"]["JobCriteria"];
            /**
             * Pack
             * @description Curated company pack used for first-party job discovery.
             * @default backend_india
             */
            pack: string;
            /**
             * Provider Consent
             * @description Explicit consent to send bounded resume excerpts to the configured paid model provider under the disclosed retention terms.
             * @constant
             */
            provider_consent: true;
            /**
             * Resume Text
             * @description Plain-text resume body.
             */
            resume_text: string;
            /**
             * Use Self Rag
             * @description Toggle V8 self-RAG. Set False for the V10 round-1 baseline so the demo can compare drafts with and without past-trace exemplars.
             * @default true
             */
            use_self_rag: boolean;
        };
        /**
         * HuntResult
         * @description Structured output from the end-to-end job-hunt runner.
         */
        HuntResult: {
            /**
             * Outreach
             * @description Drafted outreach messages grouped by role/person pair.
             */
            outreach: components["schemas"]["OutreachDraft"][];
            /**
             * Roles
             * @description Roles found for the supplied criteria.
             */
            roles: components["schemas"]["Role"][];
            /**
             * Run Id
             * @description Stable id for this hunt. Ties the result to its Phoenix trace and to any outcomes logged later. Generated by run_hunt() if not supplied by the caller.
             */
            run_id: string;
        };
        /**
         * JobCriteria
         * @description User-supplied filters that constrain which jobs we go fetch.
         */
        JobCriteria: {
            /**
             * Comp Max Lpa
             * @description Upper bound for comp in lakhs per annum (INR). Optional.
             */
            comp_max_lpa?: number | null;
            /**
             * Comp Min Lpa
             * @description Minimum acceptable comp in lakhs per annum (INR). Optional.
             */
            comp_min_lpa?: number | null;
            /**
             * Country
             * @description Lowercase country code used to scope source queries.
             * @default in
             */
            country: string;
            /**
             * Employment Types
             * @description Employment types accepted by the search.
             */
            employment_types?: components["schemas"]["EmploymentType"][];
            /**
             * Location
             * @description Acceptable locations. Free-form strings matched against the listing site's conventions. Example: ['Hyderabad', 'Remote-India'].
             */
            location: string[];
            /**
             * Max Age Days
             * @description Maximum listing age in days, or None to disable age filtering.
             * @default 45
             */
            max_age_days: number | null;
            /**
             * Role Keywords
             * @description Keywords that must appear in the job title or body. Example: ['SCIM', 'identity', 'IAM'].
             */
            role_keywords: string[];
            /**
             * Seniority
             * @description Seniority band the user is targeting.
             * @enum {string}
             */
            seniority: "junior" | "mid" | "senior" | "staff";
        };
        /**
         * OutcomeLog
         * @description User-logged result for one drafted message.
         */
        OutcomeLog: {
            /**
             * Draft Id
             * @description OutreachDraft.draft_id this outcome belongs to. The owning run_id is supplied by the request envelope, not the log entry.
             */
            draft_id: string;
            /**
             * Logged At
             * @description When the outcome was recorded. Server overwrites this on insert with a timezone-aware UTC timestamp.
             */
            logged_at?: string | null;
            /**
             * Notes
             * @description Optional free-text note about the outcome.
             */
            notes?: string | null;
            /**
             * Outcome
             * @description Latest user-reported status for this draft.
             * @enum {string}
             */
            outcome: "replied" | "no_reply" | "introduced" | "rejected" | "pending";
        };
        /** OutcomesRequest */
        OutcomesRequest: {
            /**
             * Outcomes
             * @description Outcome entries to append. The owning run_id comes from the URL path, not from the entries themselves.
             */
            outcomes: components["schemas"]["OutcomeLog"][];
        };
        /** OutcomesResponse */
        OutcomesResponse: {
            /** Inserted */
            inserted: number;
            /** Ok */
            ok: boolean;
            /** Outcomes */
            outcomes: components["schemas"]["OutcomeLog"][];
        };
        /**
         * OutreachDraft
         * @description One drafted outreach message for one role/person pair.
         */
        OutreachDraft: {
            /**
             * Draft Id
             * @description Stable id for this draft. Outcomes log against this id so the (run_id, draft_id) pair is the canonical join key.
             */
            draft_id?: string;
            /**
             * Eval Score
             * @description Composite 1-5 LLM-judge score written by run_hunt() (V9). None when the judge was unavailable; never blocks the pipeline.
             */
            eval_score?: number | null;
            /**
             * Message
             * @description Concise referral-request message. Plain text, no markdown, no placeholder fields.
             */
            message: string;
            /** @description Referral target this draft is addressed to. */
            person: components["schemas"]["Person"];
            /** @description Role this outreach draft is tied to. */
            role: components["schemas"]["Role"];
        };
        /**
         * Person
         * @description A plausible referral target at the hiring company.
         */
        Person: {
            /**
             * Company
             * @description Company the person currently works at. Should match Role.company for a valid referral candidate.
             */
            company: string;
            /**
             * Confidence
             * @description Confidence in the referral evidence, from 0 to 1.
             * @default 0
             */
            confidence: number;
            /**
             * Name
             * @description Person's full name as it appears on their public profile.
             */
            name: string;
            /**
             * Profile Url
             * @description URL to a public profile (LinkedIn, GitHub, or company page). Must come from a real tool result — never fabricated by the model.
             */
            profile_url: string;
            /**
             * Source
             * @description Where the profile URL came from.
             * @enum {string}
             */
            source: "linkedin" | "github" | "company_page" | "other";
            /**
             * Title
             * @description Current job title at the target company.
             */
            title: string;
            /**
             * Verified Current Employer
             * @description True only when evidence confirms the person's current employer.
             * @default false
             */
            verified_current_employer: boolean;
            /**
             * Why Relevant
             * @description One sentence on why this person is a good referral target for this specific role. Should reference something concrete about the role or the person's title — not generic praise.
             */
            why_relevant: string;
        };
        /** RequeueRequest */
        RequeueRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * Role
         * @description A single open job posting that matched the user's criteria.
         */
        Role: {
            /**
             * Apply Urls
             * @description All known apply links, with first-party links first.
             */
            apply_urls?: string[];
            /**
             * Company
             * @description Name of the hiring company.
             */
            company: string;
            /**
             * Confidence
             * @description Source-quality confidence from 0 to 1.
             * @default 1
             */
            confidence: number;
            /**
             * @description Normalized employment type reported by the source.
             * @default unknown
             */
            employment_type: components["schemas"]["EmploymentType"];
            /**
             * Fit Score
             * @description Resume-fit score from 0 to 1, when available.
             */
            fit_score?: number | null;
            /**
             * Location
             * @description Location string from the posting (city, region, or 'Remote').
             */
            location: string;
            /**
             * Match Reason
             * @description Specific justification for why this role matches the criteria. Should reference concrete details from the listing, not just echo the keywords back.
             */
            match_reason: string;
            /**
             * Posted At
             * @description Source-provided posting timestamp or date.
             */
            posted_at?: string | null;
            /**
             * Raw Description
             * @description Full job-description text used by downstream fit scoring.
             */
            raw_description?: string | null;
            /**
             * @description Source strategy that produced this role.
             * @default google_jobs
             */
            source: components["schemas"]["CompanySource"];
            /**
             * Source Updated At
             * @description Source-provided last-updated timestamp. This is not presented as the original posting date.
             */
            source_updated_at?: string | null;
            /**
             * Summary
             * @description 2-3 sentence summary of the role, extracted from the posting. Plain text, no markdown.
             */
            summary: string;
            /**
             * Title
             * @description Job title exactly as it appears on the posting.
             */
            title: string;
            /**
             * Url
             * @description Canonical URL to the job posting. Must resolve to a real page — never fabricated by the model.
             */
            url: string;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Dead Lettered At */
            dead_lettered_at?: string | null;
            /** Failed At */
            failed_at?: string | null;
            hunt_result?: components["schemas"]["HuntResult"] | null;
            /** Last Error */
            last_error?: string | null;
            /** Max Attempts */
            max_attempts: number;
            /** Outcomes */
            outcomes?: components["schemas"]["OutcomeLog"][];
            /** Queued At */
            queued_at?: string | null;
            /** Run Id */
            run_id: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "dead_letter";
        };
        /** RunStateResponse */
        RunStateResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Dead Lettered At */
            dead_lettered_at?: string | null;
            /** Failed At */
            failed_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Max Attempts */
            max_attempts: number;
            /** Queued At */
            queued_at?: string | null;
            /** Run Id */
            run_id: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "dead_letter";
        };
        /** SessionCreateRequest */
        SessionCreateRequest: {
            /** Owner Token */
            owner_token: string;
        };
        /** SessionDeleteResponse */
        SessionDeleteResponse: {
            /** Ok */
            ok: boolean;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Display Name */
            display_name: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Owner Id */
            owner_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    owner_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_hunt_api_hunt_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-Run-Access-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HuntRequestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HuntCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_outcomes_api_runs__run_id__outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requeue_run_api_runs__run_id__requeue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequeueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    create_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeleteResponse"];
                };
            };
        };
    };
    health_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
